################################################################################
# COMPREHENSIVE REGIONS CONFIGURATION FILE
################################################################################

project:
  name: "Comprehensive Regions Test"
  version: "1.0"
  market_type: "Test Market"

################################################################################
# DATA SOURCES
################################################################################
data_sources:
  # Global market forecast data
  global_forecast:
    path: "data/global_forecast.xlsx"
    sheet_name: "Sheet1"
    identifier:
      value_column: "Value"
      year_column: "Year"
      type_column: "Type"

  # Country historical data
  country_historical:
    path: "data/country_data.xlsx"
    sheet_name: "Sheet1"
    format: "wide"
    identifier:
      id_column: "idGeo"
      name_column: "Country"
      market_column: "nameVertical"

################################################################################
# COLUMN MAPPINGS
################################################################################
column_mapping:
  global_forecast:
    year_column: "Year"
    value_column: "Value"
    type_column: "Type"
  
  country_historical:
    id_column: "idGeo"
    country_column: "Country"
    vertical_column: "nameVertical"

################################################################################
# MARKET DISTRIBUTION SETTINGS
################################################################################
market_distribution:
  tier_determination: "auto"
  
  growth_constraints:
    determination_method: "auto"
  
  # Auto-calibration settings
  calibration:
    enabled: true
    accuracy_metrics: ["mape", "rmse", "r2"]
    evaluation_periods: [1, 3, 5]
    component_weights:
      tier_classification: 0.2
      causal_integration: 0.2
      gradient_harmonization: 0.15
      distribution_method: 0.3
      regional_aggregation: 0.15
    recalibration_strategy: "adaptive"
    auto_adjust_weights: true
    learning_rate: 0.15
    memory_length: 5
    apply_country_specific_adjustments: true
    confidence_thresholds:
      high: 0.85
      medium: 0.7
      low: 0.5
    save_calibration_history: true
    backup_frequency: 5

################################################################################
# REGIONAL AGGREGATION SETTINGS
################################################################################
regional_aggregation:
  enabled: true
  
  region_definitions:
    # Major Geographic Regions
    - name: "APAC"
      countries: ["Pakistan", "New Zealand", "Bangladesh", "Bhutan", "Brunei Darussalam", "Myanmar", "Cambodia", "Vietnam", "Sri Lanka", "Laos", "Taiwan", "Mongolia", "Timor-Leste", "Papua New Guinea", "Fiji", "Thailand", "South Korea", "India", "Australia", "China", "Indonesia", "Nepal", "Malaysia", "Philippines", "Singapore", "Japan"]
    
    - name: "ASEAN"
      countries: ["Indonesia", "Laos", "Brunei Darussalam", "Malaysia", "Cambodia", "Vietnam", "Thailand", "Singapore", "Myanmar", "Philippines"]
    
    - name: "Africa"
      countries: ["Western Africa", "Central Africa", "Southern Africa", "Northern Africa", "Eastern Africa"]
    
    - name: "Americas"
      countries: ["Central America", "South America", "North America", "Caribbean"]
    
    - name: "Asia"
      countries: ["Southeast Asia", "Western Asia", "Southern Asia", "Central Asia", "Eastern Asia"]
    
    - name: "Australia & Oceania"
      countries: ["Fiji", "New Zealand", "Papua New Guinea", "Australia"]
    
    # Economic Groupings
    - name: "BRICS"
      countries: ["China", "India", "Russia", "Brazil", "South Africa"]
    
    - name: "Baltics"
      countries: ["Lithuania", "Latvia", "Estonia"]
    
    - name: "Benelux"
      countries: ["Netherlands", "Luxembourg", "Belgium"]
    
    - name: "CIS"
      countries: ["Kyrgyzstan", "Armenia", "Moldova", "Russia", "Azerbaijan", "Tajikistan", "Belarus", "Kazakhstan", "Uzbekistan"]
    
    - name: "Caribbean"
      countries: ["Jamaica", "Puerto Rico", "Dominican Republic", "Haiti", "Cuba"]
    
    - name: "Central & Western Europe"
      countries: ["Hungary", "Czechia", "Switzerland", "Luxembourg", "Poland", "Netherlands", "Belgium", "Austria", "United Kingdom", "France", "Slovakia", "Germany", "Ireland"]
    
    - name: "Central Africa"
      countries: ["Republic of the Congo", "Cameroon", "Chad", "Gabon", "Equatorial Guinea", "Angola", "Democratic Republic of the Congo"]
    
    - name: "Central America"
      countries: ["El Salvador", "Nicaragua", "Honduras", "Panama", "Guatemala", "Costa Rica", "Belize"]
    
    - name: "Central Asia"
      countries: ["Tajikistan", "Uzbekistan", "Kazakhstan", "Turkmenistan", "Kyrgyzstan"]
    
    - name: "Greater China"
      countries: ["Hong Kong", "Mainland China", "Taiwan"]
    
    - name: "D-A-CH"
      countries: ["Switzerland", "Germany", "Austria"]
    
    - name: "EAEU"
      countries: ["Armenia", "Belarus", "Kazakhstan", "Kyrgyzstan", "Russia"]
    
    - name: "EMEA"
      countries: ["Spain", "Armenia", "Italy", "Hungary", "Botswana", "Burundi", "Bahrain", "Ireland", "Bosnia and Herzegovina", "Latvia", "Azerbaijan", "Belarus", "Poland", "Portugal", "Angola", "Nigeria", "Morocco", "United Kingdom", "Romania", "Switzerland", "Russia", "Serbia", "Slovakia", "Slovenia", "Norway", "Sweden", "Czechia", "Chad", "Sudan", "Zimbabwe", "Sierra Leone", "Seychelles", "South Africa", "Senegal", "Tajikistan", "Turkey", "Qatar", "Niger", "Namibia", "Oman", "Mozambique", "Montenegro", "Rwanda", "Austria", "Togo", "Tunisia", "Georgia", "Algeria", "Albania", "Zambia", "Uzbekistan", "Saudi Arabia", "United Arab Emirates", "Burkina Faso", "Egypt", "Israel", "North Macedonia", "Ukraine", "Uganda", "Turkmenistan", "Tanzania", "Belgium", "Moldova", "Mauritius", "Iceland", "Guinea", "Ghana", "Gambia", "Gabon", "Ethiopia", "Iran", "Finland", "Germany", "Equatorial Guinea", "Benin", "Cyprus", "Greece", "Republic of the Congo", "France", "Iraq", "Ivory Coast", "Estonia", "Malta", "Malawi", "Madagascar", "Bulgaria", "Croatia", "Luxembourg", "Lesotho", "Netherlands", "Lebanon", "Kyrgyzstan", "Kuwait", "Kenya", "Jordan", "Denmark", "Kazakhstan", "Cameroon", "Lithuania"]
    
    - name: "EU-27"
      countries: ["Malta", "Spain", "Belgium", "Austria", "Bulgaria", "Croatia", "Cyprus", "Czechia", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Sweden", "Luxembourg", "Romania", "Slovenia", "Slovakia", "Ireland", "Italy", "Latvia", "Lithuania", "Netherlands", "Poland", "Portugal"]
    
    - name: "Eastern Africa"
      countries: ["Malawi", "Mozambique", "South Sudan", "Kenya", "Madagascar", "Rwanda", "Zimbabwe", "Tanzania", "Ethiopia", "Uganda", "Seychelles", "Djibouti", "Zambia", "Burundi", "Somalia"]
    
    - name: "Eastern Asia"
      countries: ["South Korea", "Mongolia", "North Korea", "China", "Taiwan", "Japan"]
    
    - name: "Eastern Europe"
      countries: ["Ukraine", "Bulgaria", "Romania", "Russia", "Armenia", "Georgia", "Azerbaijan", "Moldova", "Belarus"]
    
    - name: "Europe"
      countries: ["Southern Europe", "Eastern Europe", "Central & Western Europe", "Northern Europe"]
    
    - name: "G20"
      countries: ["Malta", "Sweden", "Spain", "Slovenia", "Slovakia", "Romania", "Portugal", "Poland", "Netherlands", "Luxembourg", "Latvia", "Lithuania", "Australia", "Argentina", "Turkey", "Brazil", "Canada", "China", "Indonesia", "Japan", "South Korea", "Russia", "India", "Mexico", "Saudi Arabia", "South Africa", "United Kingdom", "Austria", "United States", "Ireland", "Hungary", "Greece", "Germany", "France", "Italy", "Finland", "Denmark", "Czechia", "Cyprus", "Croatia", "Bulgaria", "Belgium", "Estonia"]
    
    - name: "G7"
      countries: ["Canada", "Japan", "Italy", "Germany", "France", "United Kingdom", "United States"]
    
    - name: "GCC"
      countries: ["Kuwait", "Bahrain", "Qatar", "Saudi Arabia", "Oman", "United Arab Emirates"]
    
    - name: "LATAM"
      countries: ["Guyana", "Paraguay", "Jamaica", "Honduras", "Peru", "Puerto Rico", "Haiti", "Panama", "Nicaragua", "Ecuador", "El Salvador", "Dominican Republic", "Cuba", "Costa Rica", "Belize", "Bolivia", "Colombia", "Mexico", "Brazil", "Argentina", "Guatemala", "Chile", "Uruguay", "Suriname"]
    
    - name: "MENA"
      countries: ["Jordan", "Iran", "Iraq", "Turkey", "Kuwait", "Lebanon", "Oman", "Qatar", "Sudan", "United Arab Emirates", "Tunisia", "Egypt", "Algeria", "Israel", "Saudi Arabia", "Bahrain", "Morocco"]
    
    - name: "NAFTA"
      countries: ["United States", "Mexico", "Canada"]
    
    - name: "Nordics"
      countries: ["Norway", "Denmark", "Sweden", "Iceland", "Finland"]
    
    - name: "North America"
      countries: ["United States", "Mexico", "Canada"]
    
    - name: "Northern Africa"
      countries: ["Libya", "Morocco", "Algeria", "Sudan", "Egypt", "Tunisia"]
    
    - name: "Northern Europe"
      countries: ["Finland", "Lithuania", "Sweden", "Norway", "Latvia", "Denmark", "Estonia", "Iceland"]
    
    - name: "South America"
      countries: ["Venezuela", "Uruguay", "Peru", "Chile", "Argentina", "Suriname", "Bolivia", "Brazil", "Colombia", "Ecuador", "Paraguay", "Guyana"]
    
    - name: "Southeast Asia"
      countries: ["Indonesia", "Timor-Leste", "Cambodia", "Brunei Darussalam", "Laos", "Singapore", "Philippines", "Vietnam", "Myanmar", "Thailand", "Malaysia"]
    
    - name: "Southern Africa"
      countries: ["South Africa", "Namibia", "Mauritius", "Lesotho", "Botswana"]
    
    - name: "Southern Asia"
      countries: ["Nepal", "Bhutan", "Bangladesh", "Pakistan", "India", "Afghanistan", "Sri Lanka"]
    
    - name: "Southern Europe"
      countries: ["Cyprus", "Italy", "Malta", "Greece", "Montenegro", "Croatia", "North Macedonia", "Turkey", "Bosnia and Herzegovina", "Spain", "Portugal", "Serbia", "Slovenia", "Albania"]
    
    - name: "United States"
      countries: ["Louisiana", "Maine", "Kansas", "Maryland", "Massachusetts", "Nevada", "Michigan", "Minnesota", "Mississippi", "Iowa", "Missouri", "Montana", "Nebraska", "Kentucky", "New Hampshire", "New Jersey", "New Mexico", "Texas", "Tennessee", "South Dakota", "South Carolina", "Vermont", "Rhode Island", "Pennsylvania", "Oregon", "Virginia", "Oklahoma", "Ohio", "Washington", "North Carolina", "Wyoming", "New York", "Utah", "North Dakota", "Wisconsin", "Alaska", "California", "Alabama", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Arkansas", "Arizona", "West Virginia", "Hawaii", "Idaho", "Illinois", "Indiana"]
    
    - name: "Western Africa"
      countries: ["Togo", "Benin", "Niger", "Senegal", "Sierra Leone", "Burkina Faso", "Nigeria", "Guinea", "Mali", "Gambia", "Ivory Coast", "Ghana"]
    
    - name: "Western Asia"
      countries: ["Saudi Arabia", "Syria", "Iran", "Bahrain", "Kuwait", "Iraq", "Yemen", "Qatar", "Lebanon", "United Arab Emirates", "Oman", "Jordan", "Israel"]
    
  # Global Hierarchy Structure
  hierarchical:
    enabled: true
    structure:
      - name: "Worldwide"
        children:
          - name: "Americas"
            children:
              - name: "North America"
              - name: "Caribbean"
              - name: "Central America"
              - name: "South America"
          - name: "Europe"
            children:
              - name: "Northern Europe"
                children:
                  - name: "Nordics"
                  - name: "Baltics"
              - name: "Central & Western Europe"
                children:
                  - name: "Benelux"
                  - name: "D-A-CH"
              - name: "Eastern Europe"
              - name: "Southern Europe"
          - name: "Asia"
            children:
              - name: "Eastern Asia"
              - name: "Southeast Asia"
                children:
                  - name: "ASEAN"
              - name: "Southern Asia"
              - name: "Central Asia"
              - name: "Western Asia"
                children:
                  - name: "GCC"
                  - name: "MENA"
          - name: "Africa"
            children:
              - name: "Northern Africa"
              - name: "Eastern Africa"
              - name: "Central Africa"
              - name: "Western Africa"
              - name: "Southern Africa"
          - name: "Australia & Oceania"
      - name: "Economic Groupings"
        children:
          - name: "G7"
          - name: "G20"
          - name: "EU-27"
          - name: "BRICS"
          - name: "EAEU"
          - name: "CIS"
          - name: "NAFTA"
      - name: "Composite Regions"
        children:
          - name: "LATAM"
          - name: "EMEA"
          - name: "APAC"

################################################################################
# OUTPUT SETTINGS
################################################################################
output:
  save_path: "data/output"
  formats: ["xlsx", "csv", "json"]