project:
  name: Technology Market Forecaster
  version: '1.0'
  market_type: Technology Market
  description: Top-down market forecast and distribution for technology markets
data_sources:
  global_forecast:
    path: data/global_forecast.xlsx
    sheet_name: Sheet1
    identifier:
      value_column: Value
      year_column: Year
      type_column: Type
  country_historical:
    path: data/country_data.xlsx
    sheet_name: Sheet1
    format: wide
    identifier:
      id_column: idGeo
      name_column: Country
      market_column: nameVertical
  indicators:
  - name: GDP
    path: data/indicators/gdp.xlsx
    sheet_name: Sheet1
    id_column: idGeo
    country_column: nameGeo
    format: wide
    weight: auto
    type: value
  - name: TechnologyAdoption
    path: data/indicators/tech_adoption.xlsx
    sheet_name: Sheet1
    id_column: idGeo
    country_column: nameGeo
    format: wide
    weight: auto
    type: rank
column_mapping:
  global_forecast:
    year_column: Year
    value_column: Value
    type_column: Type
  country_historical:
    id_column: idGeo
    country_column: nameGeo
    vertical_column: nameVertical
  indicators:
    id_column: idGeo
    country_column: nameGeo
market_distribution:
  tier_determination: auto
  kmeans_params:
    min_clusters: 3
    max_clusters: 8
    random_state: 42
    n_init: 10
  growth_constraints:
    determination_method: auto
    manual_constraints:
      max_growth_rate: 60
      min_growth_rate: -30
      apply_scaling_by_market_size: true
  smoothing:
    enabled: true
    tier_smoothing:
      tier_1:
        window: 3
        min_periods: 1
        max_growth: 35.0
        min_growth: -15.0
        target_growth: 15.0
      tier_2:
        window: 3
        min_periods: 1
        max_growth: 40.0
        min_growth: -20.0
        target_growth: 20.0
      tier_3:
        window: 5
        min_periods: 1
        max_growth: 45.0
        min_growth: -25.0
        target_growth: 25.0
    convergence_rate: 0.25
  calibration:
    enabled: true
    recalibration_strategy: gradual
    learning_rate: 0.15
    memory_length: 5
    component_weights:
      tier_classification: 0.2
      causal_integration: 0.2
      gradient_harmonization: 0.15
      distribution_method: 0.3
      regional_aggregation: 0.15
    auto_adjust_weights: true
    apply_country_specific_adjustments: true
    confidence_thresholds:
      high: 0.85
      medium: 0.7
      low: 0.5
    evaluation_periods:
    - 1
    - 3
    - 5
    save_calibration_history: true
    backup_frequency: 5
    manual_country_adjustments: {}
weight_params:
  transformation: log
  log_base: 2.0
  log_scale: 1.0
  sigmoid_steepness: 5.0
  significance_method: continuous
  visualize_weights: false
  filtering:
    min_correlation: 0.1
    max_p_value: 0.1
    min_coverage: 0.3
output:
  save_path: data/output/
  formats:
  - xlsx
  - csv
  - json
  visualizations:
    enabled: true
    save_format: png
    dpi: 300
    types:
    - name: market_size
      title: ${market_type} Market Size by Country
      top_n_countries: 10
    - name: growth_rates
      title: ${market_type} Growth Rate Analysis
      top_n_countries: 10
      show_yoy: true
      show_cagr: true
    - name: market_share
      title: ${market_type} Market Share Analysis
      top_n_countries: 10
      show_regional: true
