################################################################################
# Universal Market Forecasting Framework - Sample Configuration with Auto-Calibration
################################################################################

# Project information
project:
  name: "Sample Market Estimator with Auto-Calibration"  # Name of your project
  version: "1.0"                                        # Version of the framework
  market_type: "Sample Market"                           # Type of market being analyzed

################################################################################
# DATA SOURCES
################################################################################
data_sources:
  # Global market forecast data
  global_forecast:
    path: "data/global_forecast.xlsx"   # Path to your global market forecast Excel file
    sheet_name: "Sheet1"                        # Name of the sheet containing the data
    identifier:
      value_column: "Value"                     # Column name containing market values
      year_column: "Year"                       # Column name containing years
      type_column: "Type"                       # Column name containing market type

  # Country historical data
  country_historical:
    path: "data/country_data.xlsx"      # Path to your country historical data Excel file
    sheet_name: "Sheet1"                        # Name of the sheet containing the data
    format: "wide"                              # Data format: "wide" or "long"
    identifier:
      id_column: "idGeo"                        # Column name containing country IDs
      name_column: "Country"                    # Column name containing country names
      market_column: "nameVertical"             # Column name containing market names

  # Indicators
  indicators:
    # Example of a regular value-based indicator
    - name: "gdp"                               # Name of the indicator
      path: "data/indicators/gdp.xlsx"       # Path to indicator data file
      sheet_name: "Sheet1"                      # Name of the sheet containing the data
      id_column: "idGeo"                        # Column name containing country IDs
      country_column: "Country"                 # Column name containing country names
      format: "wide"                            # Data format: "wide" or "long"
      weight: "auto"                            # Weight calculation method: "auto" or specific value

    # Example of a rank-based indicator
    - name: "market_rank"
      path: "data/indicators/market_rank.xlsx"
      sheet_name: "Sheet1"
      id_column: "idGeo"
      country_column: "Country"
      format: "wide"
      weight: "auto"
      type: "rank"                              # Specify this for rank-based indicators

################################################################################
# COLUMN MAPPINGS
################################################################################
column_mapping:
  global_forecast:
    year_column: "Year"                         # Column name for years in global forecast
    value_column: "Value"                       # Column name for values in global forecast
    type_column: "Type"                         # Column name for types in global forecast
  
  country_historical:
    id_column: "idGeo"                          # Column name for country IDs
    country_column: "Country"                   # Column name for country names
    vertical_column: "nameVertical"             # Column name for market names
  
  indicators:
    id_column: "idGeo"                          # Column name for country IDs in indicators
    country_column: "Country"                   # Column name for country names in indicators

################################################################################
# MARKET DISTRIBUTION SETTINGS
################################################################################
market_distribution:
  tier_determination: "auto"                    # Method for determining market tiers: "auto" or "manual"
  
  growth_constraints:
    determination_method: "auto"                # Method for determining growth constraints: "auto" or "manual"
  
  # Auto-calibration settings
  calibration:
    enabled: true                               # Enable/disable auto-calibration
    accuracy_metrics: ["mape", "rmse", "r2"]    # Metrics to use for accuracy evaluation
    evaluation_periods: [1, 3, 5]               # Years to evaluate (1-year, 3-year, 5-year)
    component_weights:                          # Initial component weights for calibration
      tier_classification: 0.2                  # Weight for tier classification
      causal_integration: 0.2                   # Weight for causal indicator integration
      gradient_harmonization: 0.15              # Weight for gradient harmonization algorithm
      distribution_method: 0.3                  # Weight for distribution method
      regional_aggregation: 0.15                # Weight for regional aggregation
    recalibration_strategy: "adaptive"          # Calibration strategy: "adaptive", "gradual", "aggressive"
    auto_adjust_weights: true                   # Auto-adjust component weights
    learning_rate: 0.15                         # Learning rate for weight adjustments
    memory_length: 5                            # Number of past calibrations to consider
    apply_country_specific_adjustments: true    # Apply country-specific adjustments
    confidence_thresholds:                      # Confidence thresholds for calibration approach
      high: 0.85                                # High confidence threshold
      medium: 0.7                               # Medium confidence threshold
      low: 0.5                                  # Low confidence threshold
    save_calibration_history: true              # Save calibration history
    backup_frequency: 5                         # Backup calibration history every N calibrations

################################################################################
# REGIONAL AGGREGATION SETTINGS
################################################################################
################################################################################
# REGIONAL AGGREGATION SETTINGS
################################################################################
regional_aggregation:
  enabled: true                                # Enable regional aggregation
  
  # A small subset of regions is included directly in this file
  # For the full list of regions, see region_definitions.yaml
  region_definitions:
    - name: "North America"
      countries: ["United States", "Canada", "Mexico"]
      
    - name: "Western Europe"
      countries: ["Germany", "France", "United Kingdom", "Italy", "Spain"]
      
    - name: "APAC"
      countries: ["China", "Japan", "South Korea", "India", "Australia"]
  
  hierarchical:
    enabled: true                              # Enable hierarchical aggregation
    structure:
      - name: "Global"
        children:
          - name: "Americas"
            children:
              - name: "North America"
              - name: "Latin America"
          - name: "EMEA"
            children:
              - name: "Western Europe"
              - name: "Eastern Europe"
              - name: "Middle East & Africa"
          - name: "Asia Pacific"
            children:
              - name: "Northeast Asia"
              - name: "Southeast Asia"
              - name: "South Asia"
              - name: "Oceania"

################################################################################
# CAUSAL INDICATOR INTEGRATION SETTINGS
################################################################################
indicators:
  enable_causal_analysis: true                  # Enable causal analysis
  apply_causal_adjustments: true                # Apply causal adjustments to distribution
  causal_analysis:
    methods: ["granger", "pcmci", "ensemble"]   # Causal analysis methods
    significance_level: 0.05                    # Significance level for causal analysis
    lag_order: 3                                # Lag order for time series analysis
    variables:                                  # Variables to include in analysis
      - "GDP"
      - "Population"
      - "Internet_Users"
    min_strength: 0.1                           # Minimum causal strength threshold

################################################################################
# GRADIENT HARMONIZATION SETTINGS
################################################################################
gradient_harmonization:
  enabled: true                                # Enable gradient harmonization
  smoothing_method: "adaptive_spline"          # Smoothing method: "adaptive_spline", "monotonic", "gaussian", "polynomial"
  smoothing_strength: 0.5                      # Smoothing strength (0-1)
  preserve_inflection_points: true             # Preserve important inflection points
  tier_specific_settings:                      # Tier-specific harmonization settings
    tier1:
      smoothing_strength: 0.3                  # Lower smoothing for tier 1 (major markets)
    tier2:
      smoothing_strength: 0.5                  # Medium smoothing for tier 2
    tier3:
      smoothing_strength: 0.7                  # Higher smoothing for tier 3 (small markets)
  detect_anomalies: true                       # Detect and correct anomalies

################################################################################
# OUTPUT SETTINGS
################################################################################
output:
  save_path: "data/output/"         # Directory where output files will be saved
  formats: ["xlsx", "csv", "json"]              # Output file formats to generate
  
  visualizations:
    types:
      # Market Size Visualization
      - name: market_size
        title: "${market_type} Market Size by Country"  # Title template with variable
        top_n_countries: 10                             # Number of top countries to show
      
      # Growth Rate Analysis
      - name: growth_rates
        title: "${market_type} Growth Rate Analysis"
        top_n_countries: 10
        show_yoy: true                                # Show year-over-year growth
        show_cagr: true                               # Show CAGR
      
      # CAGR Analysis
      - name: cagr_analysis
        title: "${market_type} CAGR Analysis"
        periods:
          - name: "Short-term"
            years: 3                                  # Period length in years
          - name: "Mid-term"
            years: 5
          - name: "Long-term"
            years: 7
      
      # Market Share Analysis
      - name: market_share
        title: "${market_type} Market Share Analysis"
        top_n_countries: 10
        show_regional: true                          # Show regional breakdown
      
      # Regional Analysis
      - name: regional_analysis
        title: "${market_type} Regional Analysis"
        specific_year: 2023                         # Base year for analysis
        analysis_years: [2023, 2024, 2025]         # Years to analyze
        regions:
          - name: "North America"                  # Region name
            countries: ["United States", "Canada"]  # Countries in the region
          - name: "Europe"
            countries: ["Germany", "France"]
          # Add more regions as needed
      
      # Top Countries Analysis
      - name: top_countries
        title: "${market_type} Top Countries Analysis"
        top_n_countries: 10
        year: 2025                                 # Year to analyze
        # specific_countries: ["Country1", "Country2"]  # Optional: specify exact countries
      
      # Forecast Comparison
      - name: forecast_comparison
        title: "${market_type} Market Forecast Comparison"
        years: [2020, 2025, 2031]                 # Years to compare in forecast
      
      # Calibration Metrics
      - name: calibration_metrics
        title: "${market_type} Forecast Calibration Metrics"
        show_accuracy_trend: true                 # Show accuracy trend over calibrations
        show_component_weights: true              # Show component weights
        show_country_errors: true                 # Show country-specific errors

################################################################################
# WEIGHT CALCULATION PARAMETERS (Optional)
################################################################################
weight_params:
  transformation: "log"                          # Weight transformation method: "log", "squared", or "sigmoid"
  log_base: 2.0                                 # Base for logarithmic transformation
  log_scale: 1.0                               # Scaling factor for logarithmic transformation
  sigmoid_steepness: 5.0                       # Steepness parameter for sigmoid transformation
  significance_method: "continuous"             # Significance adjustment method: "continuous" or "stepped"