project:
  name: "Universal Market Estimator"
  version: "1.0"
  market_type: "Machine Learning"

data_sources:
  global_forecast:
    path: "data/input/Market_Forecast.xlsx"
    identifier:
      value_column: "Value"
      year_column: "Year"
      type_column: "Type"
  
  country_historical:
    path: "data/input/Country_Historical_data.xlsx"
    identifier:
      id_column: "idGeo"
      name_column: "Country"
      market_column: "nameVertical"
  
  indicators:
    - name: "indicator1"
      path: "data/input/indicator1.xlsx"
      id_column: "idGeo"
      weight: "auto"

column_mapping:
  global_forecast:
    year_column: "Year"
    value_column: "Value"
    type_column: "Type"
  
  country_historical:
    id_column: "idGeo"
    country_column: "Country"
    vertical_column: "nameVertical"

# Market distribution configuration
market_distribution:
  # Set to "auto" for automatic tier determination or "manual" to use manual settings
  tier_determination: "auto"
  
  # Set the year from which to start redistribution
  # Historical data before this year will be preserved exactly as is
  # Set to null to redistribute all years (default behavior)
  redistribution_start_year: 2020
  
  # Manual tier settings (used if tier_determination is "manual")
  manual_tiers:
    tier1:
      description: "Market Leaders"
      share_threshold: 5.0
      max_share_change: "auto"
    tier2:
      description: "Established Markets"
      share_threshold: 1.0
      max_share_change: "auto"
  
  # Growth constraints for market share changes
  growth_constraints:
    determination_method: "auto"
    manual_constraints:
      max_growth_rate: 60
      min_growth_rate: -30
      apply_scaling_by_market_size: true

output:
  save_path: "data/output/"
  formats: ["xlsx", "csv"]
  visualizations:
    types:
      - name: "market_size"
        title: "${market_type} Market Size by Country"
        top_n_countries: 10
      - name: "market_share"
        title: "${market_type} Market Share by Country"
        top_n_countries: 10
      - name: "growth_rates"
        title: "${market_type} Growth Rates by Country"
        top_n_countries: 10 