project:
  name: "Universal Market Estimator"
  version: "1.0"
  market_type: "Semiconductor"

data_sources:
  path: "data"
  global_forecast:
    path: "data/global_forecast.xlsx"
    identifier:
      value_column: "Value"
      year_column: "Year"
      type_column: "Type"
  country_historical:
    path: "data/country_data.xlsx"
    identifier:
      id_column: "idGeo"
      name_column: "Country"
      market_column: "nameVertical"
  indicators:
    - name: "GDP"
      path: "data/indicators/gdp.xlsx"
      id_column: "idGeo"
      weight: "auto"
      type: "continuous"
    - name: "Population"
      path: "data/indicators/population.xlsx"
      id_column: "idGeo"
      weight: "auto"
      type: "continuous"
    - name: "Digital Readiness"
      path: "data/indicators/digital_readiness.xlsx"
      id_column: "idGeo"
      weight: "auto"
      type: "rank"
  
  # Causal indicator analysis settings
  enable_causal_analysis: true
  apply_causal_adjustments: true
  causal_analysis:
    method: "ensemble"  # Options: ensemble, granger, intervention, structural
    lags: 2
    alpha: 0.05
    bootstrap_samples: 100
    regularization: "elastic_net"
    interaction_detection: true
    enable_granger: true
    enable_conditional: true
    enable_feature_importance: true

column_mapping:
  global_forecast:
    year_column: "Year"
    value_column: "Value"
    type_column: "Type"
  country_historical:
    id_column: "idGeo"
    country_column: "Country"
    vertical_column: "nameVertical"
  indicators:
    id_column: "idGeo"
    country_column: "Country"
    year_column: "Year"
    value_column: "Value"

market_distribution:
  tier_determination: "auto"
  redistribution_start_year: null  # Set to a specific year (e.g., 2020) to only redistribute from that year forward
  enable_regional_aggregation: true
  regional_consistency_method: "hybrid"  # Options: top_down, bottom_up, hybrid
  manual_tiers:
    tier1:
      description: "Market Leaders"
      share_threshold: 5.0
      max_share_change: "auto"
    tier2:
      description: "Established Markets"
      share_threshold: 1.0
      max_share_change: "auto"
    tier3:
      description: "Emerging Markets"
      share_threshold: 0.1
      max_share_change: "auto"
  growth_constraints:
    determination_method: "auto"
    manual_constraints:
      max_growth_rate: 60
      min_growth_rate: -30
      apply_scaling_by_market_size: true
  # Gradient Harmonization Algorithm settings
  use_gradient_harmonization: true
  harmonization:
    method: "adaptive"  # Options: adaptive, monotonic, gaussian, polynomial
    smoothing_strength: 0.5  # 0.0 to 1.0 (higher = more smoothing)
    preserve_inflection: true  # Whether to preserve inflection points
    transition_zone: 2  # Years of transition between historical and forecast
    global_consistency: true  # Enforce global total consistency
    regional_consistency: true  # Enforce regional consistency
    boundary_enforcement: "relaxed"  # Options: strict, relaxed, none
    tier_specific_settings:
      tier1:
        smoothing_strength: 0.4  # Less smoothing for market leaders (more stable)
      tier2:
        smoothing_strength: 0.5  # Default smoothing for established markets
      tier3:
        smoothing_strength: 0.6  # More smoothing for emerging markets (more volatile)
    target_growth_rates:
      default: 15.0
      tier1: 12.0  # Lower long-term growth for mature markets
      tier2: 18.0  # Medium long-term growth for established markets
      tier3: 25.0  # Higher long-term growth for emerging markets
    endpoint_behavior: "natural"  # Options: natural, zero_slope, match_trend
    inflection_detection:
      enabled: true
      sensitivity: 0.6  # 0.0 to 1.0
      min_prominence: 0.2

output:
  save_path: "data/output/"
  formats: ["xlsx", "csv", "json"]
  visualizations:
    types:
      - name: "market_size"
        title: "${market_type} Market Size by Country"
        top_n_countries: 10
      - name: "growth_rates"
        title: "${market_type} Growth Rates"
        top_n_countries: 15
      - name: "cagr_analysis"
        title: "${market_type} CAGR Analysis"
        periods:
          - name: "Short-term"
            years: 3
          - name: "Mid-term"
            years: 5
          - name: "Long-term"
            years: 7
      - name: "regional_analysis"
        title: "${market_type} Regional Analysis"
        specific_year: null
        analysis_years: null
      - name: "causal_influence"
        title: "${market_type} Causal Indicator Influence"
        top_n_indicators: 10

regions:
  hierarchy_definition:
    APAC: ["Pakistan", "New Zealand", "Bangladesh", "Bhutan", "Brunei Darussalam", "Myanmar", "Cambodia", 
           "Vietnam", "Sri Lanka", "Mainland China", "Laos", "Taiwan", "Mongolia", "Timor-Leste", 
           "Papua New Guinea", "Fiji", "Thailand", "South Korea", "India", "Australia", "China", 
           "Hong Kong", "Indonesia", "Nepal", "Malaysia", "Philippines", "Singapore", "Japan"]
    Americas: ["Central America", "South America", "North America", "Caribbean"]
    EMEA: ["Europe", "Middle East", "Africa"]
    Worldwide: ["APAC", "Americas", "EMEA"]
  region_metadata:
    APAC: 
      description: "Asia Pacific region"
      economic_weight: 0.4
    Americas: 
      description: "North, Central, and South America"
      economic_weight: 0.35
    EMEA: 
      description: "Europe, Middle East, and Africa"
      economic_weight: 0.25
    Worldwide: 
      description: "Global total"
      economic_weight: 1.0