################################################################################
# Universal Market Forecasting Framework - Advanced Configuration With Country Boosting
################################################################################

# Project information
project:
  name: "Sample Market Estimator"                # Name of your project
  version: "1.0"                                # Version of the framework
  market_type: "Sample Market"                  # Type of market being analyzed
  description: "Configuration with all country-specific boosting options"

################################################################################
# DATA SOURCES
################################################################################
data_sources:
  # Global market forecast data
  global_forecast:
    path: "path/to/your/global_forecast.xlsx"   # Path to your global market forecast Excel file
    sheet_name: "Sheet1"                        # Name of the sheet containing the data
    identifier:
      value_column: "Value"                     # Column name containing market values
      year_column: "Year"                       # Column name containing years
      type_column: "Type"                       # Column name containing market type

  # Country historical data
  country_historical:
    path: "path/to/your/country_data.xlsx"      # Path to your country historical data Excel file
    sheet_name: "Sheet1"                        # Name of the sheet containing the data
    format: "wide"                              # Data format: "wide" or "long"
    identifier:
      id_column: "idGeo"                        # Column name containing country IDs
      name_column: "Country"                    # Column name containing country names
      market_column: "nameVertical"             # Column name containing market names

  # Indicators
  indicators:
    # Regular value-based indicator
    - name: "gdp"                               # Name of the indicator
      path: "path/to/your/gdp_data.xlsx"        # Path to indicator data file
      sheet_name: "Sheet1"                      # Name of the sheet containing the data
      id_column: "idGeo"                        # Column name containing country IDs
      country_column: "Country"                 # Column name containing country names
      format: "wide"                            # Data format: "wide" or "long"
      weight: "auto"                            # Weight calculation method: "auto" or specific value

    # Indicator with country-specific boost (higher values for target countries)
    - name: "strategic_boost"
      path: "path/to/your/strategic_boost.xlsx"  # Create an Excel file with high values for targeted countries
      sheet_name: "Sheet1"
      id_column: "idGeo"
      country_column: "Country"
      format: "wide"
      weight: 0.3                               # Give strategic indicator significant weight to boost target countries
      
    # Rank-based indicator
    - name: "market_rank"
      path: "path/to/your/rank_data.xlsx"
      sheet_name: "Sheet1"
      id_column: "idGeo"
      country_column: "Country"
      format: "wide"
      weight: "auto"
      type: "rank"                              # Specify this for rank-based indicators

    # Indicator with fixed weight
    - name: "another_indicator"
      path: "path/to/your/indicator_data.xlsx"
      sheet_name: "Sheet1"
      id_column: "idGeo"
      country_column: "Country"
      format: "wide"
      weight: 0.15                              # Fixed weight (0-1) rather than auto-calculated
      type: "value"                             # (Optional) Type of indicator

################################################################################
# COLUMN MAPPINGS
################################################################################
column_mapping:
  global_forecast:
    year_column: "Year"                         # Column name for years in global forecast
    value_column: "Value"                       # Column name for values in global forecast
    type_column: "Type"                         # Column name for types in global forecast
  
  country_historical:
    id_column: "idGeo"                          # Column name for country IDs
    country_column: "Country"                   # Column name for country names
    vertical_column: "nameVertical"             # Column name for market names
  
  indicators:
    id_column: "idGeo"                          # Column name for country IDs in indicators
    country_column: "Country"                   # Column name for country names in indicators

################################################################################
# MARKET DISTRIBUTION SETTINGS
################################################################################
market_distribution:
  # OPTION 1: Manual tier assignment with country lists
  tier_determination: "manual"                  # Use "manual" to explicitly assign countries to tiers
  
  # Manual tier configuration with explicit country assignments
  manual_tiers:
    tier_1:
      share_threshold: 5.0                      # Share threshold for auto-assignment based on market share
      description: "Market Leaders"             # Description of this tier
      countries: [                              # Explicitly assign countries to this tier regardless of share
        "Norway",                               # Countries listed here will be boosted to top tier
        "Sweden", 
        "Country_To_Boost_1", 
        "Country_To_Boost_2"
      ]
      # Tier-specific growth settings
      max_share_change: 25                      # Maximum share change allowed per year (%)
      target_growth: 25                         # Long-term target growth rate (%)
    
    tier_2:
      share_threshold: 1.0                      # Countries with >= 1% and < 5% share
      description: "Established Markets"
      countries: ["Country_3", "Country_4"]     # Override automatic assignment for these countries
      max_share_change: 15                      # Lower change limit for tier 2
      target_growth: 15                         # Lower target growth for tier 2
    
    tier_3:
      share_threshold: 0.1                      # Countries with >= 0.1% and < 1% share
      description: "Emerging Markets"
      # No explicit country assignments, will use threshold-based assignment
  
  # OPTION 2: K-means clustering parameters (used if tier_determination is "auto")
  kmeans_params:
    min_clusters: 3                             # Minimum number of clusters (tiers)
    max_clusters: 8                             # Maximum number of clusters (tiers)
    random_state: 42                            # Random seed for reproducibility
    n_init: 10                                  # Number of times K-means is run with different seeds
  
  # OPTION 3: Growth constraints settings
  growth_constraints:
    determination_method: "manual"              # Method: "auto" (data-driven) or "manual"
    
    # Manual growth constraints
    manual_constraints:
      max_growth_rate: 60                       # Maximum allowed year-over-year growth rate (%)
      min_growth_rate: -15                      # Minimum allowed year-over-year growth rate (%)
      apply_scaling_by_market_size: true        # Whether to scale constraints by market size
    
    # Country-specific growth constraints
    country_specific_constraints:
      "Norway":                                 # Target country to boost
        max_growth_rate: 80                     # Higher maximum growth rate for this country
        min_growth_rate: 5                      # Ensure positive growth (prevent decline)
      "Sweden":
        max_growth_rate: 75
        min_growth_rate: 0
      "Country_To_Boost_1":
        max_growth_rate: 70
        min_growth_rate: 0
  
  # OPTION 4: Smoothing algorithm parameters
  smoothing:
    enabled: true                               # Whether to apply smoothing to growth trajectories
    
    # Tier-specific smoothing parameters
    tier_smoothing:
      tier_1:                                   # Parameters for top tier (market leaders)
        window: 3                               # Rolling average window
        min_periods: 1                          # Minimum periods for rolling calculations
        max_growth: 45                          # Maximum growth after smoothing (%)
        min_growth: 0                           # Minimum growth after smoothing (%) - prevent negative
        target_growth: 30                       # Long-term target growth rate (%)
      
      tier_2:                                   # Parameters for middle tier (established markets)
        window: 3
        min_periods: 1
        max_growth: 35
        min_growth: -10
        target_growth: 20
      
      tier_3:                                   # Parameters for bottom tier (emerging markets)
        window: 5
        min_periods: 1
        max_growth: 30
        min_growth: -20
        target_growth: 15
    
    # Country-specific smoothing overrides
    country_smoothing:
      "Norway":                                 # Target country to boost
        max_growth: 60                          # Much higher max growth for this specific country
        min_growth: 10                          # Ensure strong positive growth
        target_growth: 40                       # Higher long-term target
      "Sweden":
        max_growth: 50
        min_growth: 5
        target_growth: 35
    
    convergence_rate: 0.25                      # How quickly growth rates converge to target values
  
  # OPTION 5: Base share adjustment (globally boost certain countries)
  base_share_adjustments:
    enabled: true                               # Enable manual share adjustments
    adjustments:
      "Norway": 1.5                             # Multiply base share by 1.5 (50% increase)
      "Sweden": 1.3                             # 30% increase for Sweden
      "Country_To_Boost_1": 1.2                 # 20% increase for another country
  
  # OPTION 6: Share trend boosting
  trend_boosting:
    enabled: true                               # Enable trend boosting
    boost_factors:
      "Norway": 1.3                             # Boost trend factor by 30%
      "Sweden": 1.2                             # Boost trend factor by 20%
    
    # Allows setting absolute trend factors for specific countries
    absolute_trends:
      "Country_To_Boost_2": 1.15                # Set absolute trend factor (15% annual growth)

################################################################################
# WEIGHT CALCULATION PARAMETERS
################################################################################
weight_params:
  # Transformation method for correlations
  transformation: "log"                          # Options: "log", "squared", "sigmoid"
  
  # Log transformation parameters (used if transformation is "log")
  log_base: 2.0                                 # Base for logarithmic transformation
  log_scale: 1.0                                # Scaling factor for logarithmic transformation
  
  # Sigmoid transformation parameters (used if transformation is "sigmoid")
  sigmoid_steepness: 5.0                        # Steepness parameter for sigmoid transformation
  
  # Significance adjustment method
  significance_method: "continuous"             # Options: "continuous" or "stepped"
  
  # OPTION 7: Indicator weights for country boosting
  country_specific_weights:
    enabled: true                               # Enable country-specific indicator weights
    adjustments:
      "Norway":                                 # Target country to boost
        "gdp": 0.8                              # If Norway has high GDP, giving GDP more weight helps boost Norway
        "market_rank": 0.2                      # Lower weight for indicators where Norway might not perform well
      "Sweden":
        "gdp": 0.7
        "market_rank": 0.3
  
  # Enable visualization of weight comparisons
  visualize_weights: true                       # Whether to generate weight comparison charts
  
  # Filter settings for indicators
  filtering:
    min_correlation: 0.1                        # Minimum correlation to consider (absolute value)
    max_p_value: 0.1                            # Maximum p-value to consider significant
    min_coverage: 0.3                           # Minimum data coverage ratio required

################################################################################
# OUTPUT SETTINGS
################################################################################
output:
  save_path: "path/to/output/directory"         # Directory where output files will be saved
  formats: ["xlsx", "csv", "json"]              # Output file formats to generate
  
  # OPTION 8: Country filtering for output files
  country_filtering:
    enabled: false                               # Whether to filter countries in output
    include_only: ["Norway", "Sweden", "Denmark", "Finland"]  # Only include these countries
    exclude: ["Country_To_Exclude_1", "Country_To_Exclude_2"]  # Exclude these countries
  
  visualizations:
    enabled: true                               # Enable visualization generation
    save_format: "png"                          # Image format: "png", "jpg", "svg", "pdf"
    dpi: 300                                    # Resolution for raster formats
    custom_style: "seaborn-whitegrid"           # Matplotlib style (optional)
    
    types:
      # Market Size Visualization with highlight countries
      - name: market_size
        title: "${market_type} Market Size by Country"  # Title template with variable
        top_n_countries: 10                             # Number of top countries to show
        specific_years: [2023, 2025, 2030]              # Specific years to visualize
        show_cagr: true                                 # Show CAGR on the chart
        stacked: false                                  # Whether to use stacked bar chart
        highlight_countries: ["Norway", "Sweden"]       # Highlight these countries with different color
      
      # Growth Rate Analysis focusing on specific countries
      - name: growth_rates
        title: "${market_type} Growth Rate Analysis"
        top_n_countries: 5                              # Only show top 5
        show_yoy: true                                  # Show year-over-year growth
        show_cagr: true                                 # Show CAGR
        highlight_outliers: true                        # Highlight unusual growth patterns
        specific_countries: ["Norway", "Sweden", "Finland"]  # Only show these countries
      
      # CAGR Analysis
      - name: cagr_analysis
        title: "${market_type} CAGR Analysis"
        periods:
          - name: "Short-term"
            years: 3                                    # Period length in years
          - name: "Mid-term" 
            years: 5
          - name: "Long-term"
            years: 7
        specific_countries: ["Norway", "Sweden", "Finland", "Denmark"]  # Focus on Nordic countries
      
      # Market Share Analysis
      - name: market_share
        title: "${market_type} Market Share Analysis"
        top_n_countries: 10
        show_regional: true                            # Show regional breakdown
        specific_years: [2023, 2030]                   # Specific years for analysis
      
      # Regional Analysis with customized regions
      - name: regional_analysis
        title: "${market_type} Regional Analysis"
        specific_year: 2023                           # Base year for analysis
        analysis_years: [2023, 2025, 2030]            # Years to analyze
        regions:
          - name: "Nordic Countries"                  # Custom region focusing on target countries
            countries: ["Norway", "Sweden", "Denmark", "Finland", "Iceland"]
          - name: "North America"
            countries: ["United States", "Canada", "Mexico"]
          - name: "Europe"
            countries: ["Germany", "France", "UK", "Italy", "Spain"]
          - name: "Asia Pacific"
            countries: ["China", "Japan", "India", "South Korea", "Australia"]
          - name: "Rest of World"
            countries: ["Brazil", "South Africa", "Russia", "Saudi Arabia"]
      
      # Top Countries Analysis
      - name: top_countries
        title: "${market_type} Top Countries Analysis"
        top_n_countries: 10
        year: 2025                                    # Year to analyze
        specific_countries: ["Norway", "Sweden", "Denmark", "Finland"]  # Override to show specific countries
      
      # Forecast Comparison
      - name: forecast_comparison
        title: "${market_type} Market Forecast Comparison"
        years: [2020, 2025, 2030]                     # Years to compare in forecast
        include_historical: true                      # Include historical data for comparison
        confidence_interval: 0.9                      # Show confidence interval (0-1)
        specific_countries: ["Norway", "Global"]      # Compare specific country vs global

################################################################################
# ADVANCED ANALYSIS SETTINGS
################################################################################
advanced:
  # OPTION 9: Post-processing adjustments
  post_processing:
    enabled: true                               # Enable post-processing adjustments
    country_multipliers:                        # Direct multipliers for country values
      "Norway": 1.5                             # Multiply Norway's values by 1.5 (50% increase)
      "Sweden": 1.3                             # 30% increase for Sweden
      "Denmark": 1.2                            # 20% increase for Denmark
    
    adjust_shares: true                         # Whether to recalculate market shares after adjustment
  
  # Sensitivity analysis
  sensitivity_analysis:
    enabled: false                              # Whether to run sensitivity analysis
    variables:                                  # Variables to analyze sensitivity for
      - name: "global_market_size"
        range: [-10, 10]                        # Percent range to vary
        steps: 5                                # Number of steps within range
      - name: "growth_rate"
        range: [-5, 5]
        steps: 3
  
  # Outlier detection and handling
  outlier_detection:
    enabled: true                               # Whether to detect outliers
    method: "iqr"                               # Method: "iqr", "z_score", or "isolation_forest"
    threshold: 1.5                              # Threshold for outlier detection
    action: "cap"                               # Action: "cap", "remove", or "flag"
  
  # Custom extension hooks
  extensions:
    pre_analysis: "path/to/custom_script.py"    # Script to run before analysis
    post_processing: "path/to/custom_script.py" # Script to run after processing
    custom_country_boost: "path/to/country_boost.py"  # Custom script for country-specific adjustments
    
  # Parallelization settings for large datasets
  parallel_processing:
    enabled: false                              # Whether to use parallel processing
    n_jobs: -1                                  # Number of jobs (-1 for all processors)
    backend: "multiprocessing"                  # Backend: "multiprocessing" or "threading" 