################################################################################
# Universal Market Forecasting Framework - Sample Configuration File
################################################################################

# Project information
project:
  name: "Sample Market Estimator"  # Name of your project
  version: "1.0"                  # Version of the framework
  market_type: "Sample Market"     # Type of market being analyzed

################################################################################
# DATA SOURCES
################################################################################
data_sources:
  # Global market forecast data
  global_forecast:
    path: "path/to/your/global_forecast.xlsx"   # Path to your global market forecast Excel file
    sheet_name: "Sheet1"                        # Name of the sheet containing the data
    identifier:
      value_column: "Value"                     # Column name containing market values
      year_column: "Year"                       # Column name containing years
      type_column: "Type"                       # Column name containing market type

  # Country historical data
  country_historical:
    path: "path/to/your/country_data.xlsx"      # Path to your country historical data Excel file
    sheet_name: "Sheet1"                        # Name of the sheet containing the data
    format: "wide"                              # Data format: "wide" or "long"
    identifier:
      id_column: "idGeo"                        # Column name containing country IDs
      name_column: "Country"                    # Column name containing country names
      market_column: "nameVertical"             # Column name containing market names

  # Indicators
  indicators:
    # Example of a regular value-based indicator
    - name: "gdp"                               # Name of the indicator
      path: "path/to/your/gdp_data.xlsx"       # Path to indicator data file
      sheet_name: "Sheet1"                      # Name of the sheet containing the data
      id_column: "idGeo"                        # Column name containing country IDs
      country_column: "Country"                 # Column name containing country names
      format: "wide"                            # Data format: "wide" or "long"
      weight: "auto"                            # Weight calculation method: "auto" or specific value

    # Example of a rank-based indicator
    - name: "market_rank"
      path: "path/to/your/rank_data.xlsx"
      sheet_name: "Sheet1"
      id_column: "idGeo"
      country_column: "Country"
      format: "wide"
      weight: "auto"
      type: "rank"                              # Specify this for rank-based indicators

################################################################################
# COLUMN MAPPINGS
################################################################################
column_mapping:
  global_forecast:
    year_column: "Year"                         # Column name for years in global forecast
    value_column: "Value"                       # Column name for values in global forecast
    type_column: "Type"                         # Column name for types in global forecast
  
  country_historical:
    id_column: "idGeo"                          # Column name for country IDs
    country_column: "nameGeo"                   # Column name for country names
    vertical_column: "nameVertical"             # Column name for market names
  
  indicators:
    id_column: "idGeo"                          # Column name for country IDs in indicators
    country_column: "nameGeo"                   # Column name for country names in indicators

################################################################################
# MARKET DISTRIBUTION SETTINGS
################################################################################
market_distribution:
  tier_determination: "auto"                    # Method for determining market tiers: "auto" or "manual"
  
  growth_constraints:
    determination_method: "auto"                # Method for determining growth constraints: "auto" or "manual"

################################################################################
# OUTPUT SETTINGS
################################################################################
output:
  save_path: "path/to/output/directory"         # Directory where output files will be saved
  formats: ["xlsx", "csv", "json"]              # Output file formats to generate
  
  visualizations:
    types:
      # Market Size Visualization
      - name: market_size
        title: "${market_type} Market Size by Country"  # Title template with variable
        top_n_countries: 10                             # Number of top countries to show
      
      # Growth Rate Analysis
      - name: growth_rates
        title: "${market_type} Growth Rate Analysis"
        top_n_countries: 10
        show_yoy: true                                # Show year-over-year growth
        show_cagr: true                               # Show CAGR
      
      # CAGR Analysis
      - name: cagr_analysis
        title: "${market_type} CAGR Analysis"
        periods:
          - name: "Short-term"
            years: 3                                  # Period length in years
          - name: "Mid-term"
            years: 5
          - name: "Long-term"
            years: 7
      
      # Market Share Analysis
      - name: market_share
        title: "${market_type} Market Share Analysis"
        top_n_countries: 10
        show_regional: true                          # Show regional breakdown
      
      # Regional Analysis
      - name: regional_analysis
        title: "${market_type} Regional Analysis"
        specific_year: 2023                         # Base year for analysis
        analysis_years: [2023, 2024, 2025]         # Years to analyze
        regions:
          - name: "North America"                  # Region name
            countries: ["United States", "Canada"]  # Countries in the region
          - name: "Europe"
            countries: ["Germany", "France"]
          # Add more regions as needed
      
      # Top Countries Analysis
      - name: top_countries
        title: "${market_type} Top Countries Analysis"
        top_n_countries: 10
        year: 2025                                 # Year to analyze
        # specific_countries: ["Country1", "Country2"]  # Optional: specify exact countries
      
      # Forecast Comparison
      - name: forecast_comparison
        title: "${market_type} Market Forecast Comparison"
        years: [2020, 2025, 2031]                 # Years to compare in forecast

################################################################################
# WEIGHT CALCULATION PARAMETERS (Optional)
################################################################################
weight_params:
  transformation: "log"                          # Weight transformation method: "log", "squared", or "sigmoid"
  log_base: 2.0                                 # Base for logarithmic transformation
  log_scale: 1.0                               # Scaling factor for logarithmic transformation
  sigmoid_steepness: 5.0                       # Steepness parameter for sigmoid transformation
  significance_method: "continuous"             # Significance adjustment method: "continuous" or "stepped"